# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-12-03 04:31
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('input', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userrole',
            old_name='username',
            new_name='user',
        ),
    ]
