# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-12-11 01:47
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('input', '0002_auto_20181203_1231'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='barcode',
            field=models.CharField(max_length=300, verbose_name='条码'),
        ),
        migrations.AlterField(
            model_name='item',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='item',
            name='name',
            field=models.CharField(max_length=300, verbose_name='名称'),
        ),
        migrations.AlterField(
            model_name='item',
            name='nr',
            field=models.CharField(max_length=300, unique=True, verbose_name='代码'),
        ),
        migrations.AlterField(
            model_name='perm',
            name='codename',
            field=models.CharField(max_length=300, unique=True, verbose_name='名称代码'),
        ),
        migrations.AlterField(
            model_name='perm',
            name='name',
            field=models.CharField(max_length=300, unique=True, verbose_name='名称'),
        ),
        migrations.AlterField(
            model_name='role',
            name='name',
            field=models.CharField(max_length=300, unique=True, verbose_name='角色名称'),
        ),
        migrations.AlterField(
            model_name='rolepermission',
            name='permission',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='input.Perm', verbose_name='权限'),
        ),
        migrations.AlterField(
            model_name='rolepermission',
            name='role',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='input.Role', verbose_name='角色'),
        ),
        migrations.AlterField(
            model_name='userrole',
            name='role',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='input.Role', verbose_name='角色'),
        ),
        migrations.AlterField(
            model_name='userrole',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='用户'),
        ),
    ]
