# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2019-01-08 09:37
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('input', '0002_auto_20190107_1839'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='lft',
        ),
        migrations.RemoveField(
            model_name='item',
            name='lvl',
        ),
        migrations.RemoveField(
            model_name='item',
            name='rght',
        ),
        migrations.AlterField(
            model_name='tree_model',
            name='effective_start',
            field=models.DateField(blank=True, default=datetime.datetime(2019, 1, 8, 0, 0), null=True, verbose_name='生效开始'),
        ),
    ]
