# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-12-18 04:31
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('input', '0005_auto_20181211_1903'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='effective_end',
            field=models.DateField(blank=True, default=datetime.datetime(2030, 12, 31, 0, 0), null=True, verbose_name='生效结束'),
        ),
        migrations.AddField(
            model_name='item',
            name='effective_start',
            field=models.DateField(blank=True, default=datetime.datetime(2018, 12, 18, 0, 0), null=True, verbose_name='生效开始'),
        ),
        migrations.AddField(
            model_name='item',
            name='lft',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='左节点'),
        ),
        migrations.AddField(
            model_name='item',
            name='lvl',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='层级'),
        ),
        migrations.AddField(
            model_name='item',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='xchildren', to='input.Item', verbose_name='父类'),
        ),
        migrations.AddField(
            model_name='item',
            name='rght',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='右节点'),
        ),
    ]
