# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-12-19 04:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('input', '0007_auto_20181219_1024'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='ancestor',
        ),
        migrations.AddField(
            model_name='item',
            name='number',
            field=models.IntegerField(blank=True, null=True, verbose_name='数量'),
        ),
        migrations.AddField(
            model_name='item',
            name='unit',
            field=models.CharField(blank=True, max_length=300, null=True, verbose_name='单位'),
        ),
    ]
