# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-12-19 04:20
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('input', '0008_auto_20181219_1207'),
    ]

    operations = [
        migrations.RenameField(
            model_name='item',
            old_name='number',
            new_name='qty',
        ),
    ]
