# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-12-19 07:12
from __future__ import unicode_literals

from django.db import migrations
import django.db.models.deletion
import mptt.fields


class Migration(migrations.Migration):

    dependencies = [
        ('input', '0010_tree_model'),
    ]

    operations = [
        migrations.AddField(
            model_name='tree_model',
            name='parent',
            field=mptt.fields.TreeForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='input.Tree_Model'),
        ),
    ]
