# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-12-19 07:29
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('input', '0011_tree_model_parent'),
    ]

    operations = [
        migrations.AddField(
            model_name='tree_model',
            name='barcode',
            field=models.CharField(blank=True, max_length=300, null=True, verbose_name='条码'),
        ),
        migrations.AddField(
            model_name='tree_model',
            name='effective_end',
            field=models.DateField(blank=True, default=datetime.datetime(2030, 12, 31, 0, 0), null=True, verbose_name='生效结束'),
        ),
        migrations.AddField(
            model_name='tree_model',
            name='effective_start',
            field=models.DateField(blank=True, default=datetime.datetime(2018, 12, 19, 0, 0), null=True, verbose_name='生效开始'),
        ),
        migrations.AddField(
            model_name='tree_model',
            name='qty',
            field=models.IntegerField(blank=True, null=True, verbose_name='数量'),
        ),
        migrations.AddField(
            model_name='tree_model',
            name='unit',
            field=models.CharField(blank=True, max_length=300, null=True, verbose_name='单位'),
        ),
        migrations.AlterField(
            model_name='tree_model',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
