# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-12-21 10:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('input', '0013_auto_20181221_1359'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tree_model',
            name='nr',
            field=models.CharField(max_length=300, verbose_name='代码'),
        ),
    ]
