# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-12-24 01:51
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('input', '0014_auto_20181221_1821'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='effective_start',
            field=models.DateField(blank=True, default=datetime.datetime(2018, 12, 24, 0, 0), null=True, verbose_name='生效开始'),
        ),
        migrations.AlterField(
            model_name='tree_model',
            name='effective_start',
            field=models.DateField(blank=True, default=datetime.datetime(2018, 12, 24, 0, 0), null=True, verbose_name='生效开始'),
        ),
        migrations.AlterField(
            model_name='tree_model',
            name='name',
            field=models.CharField(blank=True, max_length=300, null=True, verbose_name='名称'),
        ),
    ]
