# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-12-24 03:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('input', '0015_auto_20181224_0951'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tree_model',
            name='name',
            field=models.CharField(max_length=300, verbose_name='名称'),
        ),
    ]
