# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-12-25 04:00
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('input', '0016_auto_20181224_1111'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='effective_start',
            field=models.DateField(blank=True, default=datetime.datetime(2018, 12, 25, 0, 0), null=True, verbose_name='生效开始'),
        ),
        migrations.AlterField(
            model_name='tree_model',
            name='effective_start',
            field=models.DateField(blank=True, default=datetime.datetime(2018, 12, 25, 0, 0), null=True, verbose_name='生效开始'),
        ),
        migrations.AlterField(
            model_name='tree_model',
            name='nr',
            field=models.CharField(blank=True, max_length=300, null=True, verbose_name='代码'),
        ),
        migrations.AlterField(
            model_name='tree_model',
            name='qty',
            field=models.IntegerField(verbose_name='数量'),
        ),
    ]
