# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-12-27 06:54
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('input', '0020_auto_20181226_1636'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='effective_start',
            field=models.DateField(blank=True, default=datetime.datetime(2018, 12, 27, 0, 0), null=True, verbose_name='生效开始'),
        ),
        migrations.AlterField(
            model_name='tree_model',
            name='effective_start',
            field=models.DateField(blank=True, default=datetime.datetime(2018, 12, 27, 0, 0), null=True, verbose_name='生效开始'),
        ),
        migrations.AlterField(
            model_name='tree_model',
            name='nr',
            field=models.CharField(max_length=300, unique=True, verbose_name='代码'),
        ),
    ]
