# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2019-01-04 05:40
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('input', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BomModel',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nr', models.CharField(max_length=300, unique=True, verbose_name='代码')),
                ('qty', models.IntegerField(verbose_name='数量')),
                ('effective_start', models.DateField(blank=True, default=datetime.datetime(2019, 1, 4, 0, 0), null=True, verbose_name='生效开始')),
                ('effective_end', models.DateField(blank=True, default=datetime.datetime(2030, 12, 31, 0, 0), null=True, verbose_name='生效结束')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bom_item', to='input.Item', verbose_name='物料')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='bom_parent', to='input.Item', verbose_name='父类')),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='bommodel',
            unique_together=set([('item', 'parent')]),
        ),
    ]
