# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2019-01-07 10:39
from __future__ import unicode_literals

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('my_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='identifier')),
                ('object_pk', models.TextField(verbose_name='object id')),
                ('comment', models.TextField(max_length=3000, verbose_name='comment')),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='content_type', to='contenttypes.ContentType', verbose_name='content type')),
                ('user', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='user')),
            ],
        ),
        migrations.AlterField(
            model_name='bommodel',
            name='effective_start',
            field=models.DateField(blank=True, default=datetime.datetime(2019, 1, 7, 0, 0), null=True, verbose_name='生效开始'),
        ),
    ]
