# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2019-01-08 09:37
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0002_auto_20190107_1839'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pictures',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pic', models.ImageField(upload_to='picture/')),
            ],
        ),
        migrations.RemoveField(
            model_name='comment',
            name='content_type',
        ),
        migrations.RemoveField(
            model_name='comment',
            name='user',
        ),
        migrations.AlterField(
            model_name='bommodel',
            name='effective_start',
            field=models.DateField(blank=True, default=datetime.datetime(2019, 1, 8, 0, 0), null=True, verbose_name='生效开始'),
        ),
        migrations.DeleteModel(
            name='Comment',
        ),
    ]
