# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2019-01-09 06:28
from __future__ import unicode_literals

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('contenttypes', '0002_remove_content_type_name'),
        ('my_app', '0003_auto_20190108_1737'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='identifier')),
                ('object_pk', models.TextField(verbose_name='object id')),
                ('img', models.ImageField(blank=True, null=True, upload_to='img', verbose_name='图片')),
                ('file', models.FileField(blank=True, null=True, upload_to='file', verbose_name='文件')),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='content_type', to='contenttypes.ContentType', verbose_name='content type')),
                ('user', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='user')),
            ],
        ),
        migrations.AlterField(
            model_name='bommodel',
            name='effective_start',
            field=models.DateField(blank=True, default=datetime.datetime(2019, 1, 9, 0, 0), null=True, verbose_name='生效开始'),
        ),
    ]
