# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2019-01-09 07:23
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0004_auto_20190109_1428'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='upload_time',
            field=models.DateField(blank=True, default=datetime.datetime(2019, 1, 9, 15, 23, 48, 423149), null=True, verbose_name='上传时间'),
        ),
    ]
