# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2019-01-09 08:59
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0005_comment_upload_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='upload_time',
            field=models.DateField(blank=True, default=datetime.datetime(2019, 1, 9, 8, 59, 24, 773446, tzinfo=utc), null=True, verbose_name='上传时间'),
        ),
    ]
