# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2019-01-10 01:35
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0007_auto_20190109_1721'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bommodel',
            name='effective_start',
            field=models.DateField(blank=True, default=datetime.datetime(2019, 1, 10, 0, 0), null=True, verbose_name='生效开始'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='upload_time',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2019, 1, 10, 1, 35, 43, 673082, tzinfo=utc), null=True, verbose_name='上传时间'),
        ),
    ]
