# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2019-01-10 08:22
from __future__ import unicode_literals

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('contenttypes', '0002_remove_content_type_name'),
        ('my_app', '0008_auto_20190110_0935'),
    ]

    operations = [
        migrations.CreateModel(
            name='UploadFileModel',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='identifier')),
                ('object_pk', models.TextField(verbose_name='object id')),
                ('img', models.CharField(blank=True, max_length=500, null=True, verbose_name='图片')),
                ('file', models.CharField(blank=True, max_length=500, null=True, verbose_name='文件')),
                ('upload_time', models.DateTimeField(blank=True, default=datetime.datetime(2019, 1, 10, 8, 22, 16, 685157, tzinfo=utc), null=True, verbose_name='上传时间')),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='upload_file', to='contenttypes.ContentType', verbose_name='content type')),
                ('user', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='user')),
            ],
        ),
        migrations.AlterField(
            model_name='comment',
            name='upload_time',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2019, 1, 10, 8, 22, 16, 684156, tzinfo=utc), null=True, verbose_name='上传时间'),
        ),
    ]
