# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2019-01-10 08:37
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0009_auto_20190110_1622'),
    ]

    operations = [
        migrations.AddField(
            model_name='uploadfilemodel',
            name='file_url',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='文件地址'),
        ),
        migrations.AddField(
            model_name='uploadfilemodel',
            name='img_url',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='图片'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='upload_time',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2019, 1, 10, 8, 37, 8, 258152, tzinfo=utc), null=True, verbose_name='上传时间'),
        ),
        migrations.AlterField(
            model_name='uploadfilemodel',
            name='upload_time',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2019, 1, 10, 8, 37, 8, 259152, tzinfo=utc), null=True, verbose_name='上传时间'),
        ),
    ]
